/**
 * Seeds a workspace at any stage, in any state that stage can be in.
 *
 * `scripts/seed-demo.ts` gets one fixed workspace to an early stage so the app
 * has something real to open onto. This generalises that: name any stage and
 * any state it can be in, and the script drives a fresh project there through
 * the same command engine a person or a build worker would use
 * (`apps/hub/src/engine.ts`'s `execute`) — never a direct row write. What
 * comes out the other end is a state the product could actually reach.
 *
 * Usage:
 *   bun scripts/seed-workspace.ts --stage 4 --state waiting_approval
 *   bun scripts/seed-workspace.ts --stage 8 --state interrupted   # parked mid-attempt
 *   bun scripts/seed-workspace.ts --list                          # every seedable combination
 *
 * Determinism: every artifact body, project policy and title is fixed text —
 * nothing timestamped or random goes into what is seeded. The project's own
 * ids are still generated by the product (`apps/hub/src/ids.ts` uses
 * `crypto.getRandomValues`, and this script does not touch that), so two runs
 * do not produce byte-identical ids — they produce the same stage, the same
 * state, the same artifacts and the same policy every time, which is what
 * "the same command twice gives the same workspace" means here. Because the
 * title is fixed per stage/state pair, a run first tombstones any project
 * already seeded under that title, so re-seeding does not pile up duplicates.
 *
 * See SEEDING.md for what can and cannot be seeded, and why.
 */
import { openDatabase } from "../apps/hub/src/db.js";
import { prepareDatabase } from "../apps/hub/src/migrate.js";
import { ensureHub, localActor } from "../apps/hub/src/hub-client.js";
import { install } from "./host-install.js";
import {
  createProject,
  listProjects,
  projectDetail,
  writeArtifact,
} from "../apps/hub/src/projects.js";
import { execute, HOST_PRINCIPAL, type Actor, type CommandOutcome } from "../apps/hub/src/engine.js";
import { newId } from "../apps/hub/src/ids.js";
import { databaseDirectory } from "../apps/hub/src/paths.js";
import { workspaceFor } from "../apps/hub/src/corbits-exec.js";
import { judgeCompletion, verifierReportOf, type VerifierReport } from "../apps/hub/src/completion-judge.js";
import { HostError } from "../apps/hub/src/errors.js";
import type { ArtifactKind } from "../apps/hub/src/domain.js";
import type { Command, Stage } from "@solutions-builder/app/ledger";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { createHash } from "node:crypto";

// --- argv -------------------------------------------------------------

function usage(): never {
  console.log(`Usage: bun scripts/seed-workspace.ts --stage <1-9> --state <name>
       bun scripts/seed-workspace.ts --list

Seeds one project so it sits at the named stage, in the named state, with the
state that stage would actually carry: approved artifacts from every earlier
stage, recorded approvals, audience decisions where stage 5 needs them.

--list prints every stage/state combination this script can seed, and why the
ones it refuses cannot be reached.`);
  process.exit(1);
}

function arg(name: string): string | undefined {
  const index = process.argv.indexOf(`--${name}`);
  return index === -1 ? undefined : process.argv[index + 1];
}

const LIST = process.argv.includes("--list");

// --- fixed content, no timestamps, no randomness -----------------------

const ARTIFACTS_FOR_STAGE: Record<
  1 | 2 | 3 | 4 | 5 | 6 | 7,
  { kind: ArtifactKind; title: string; body: string }[]
> = {
  1: [
    {
      kind: "problem_brief",
      title: "Problem brief",
      body: `# Problem brief

## Problem statement
Playing chess against an engine is not fun. Stockfish wins in twenty moves and
teaches nothing; the "easy" levels blunder in ways no human would, which is
just as unenjoyable in a different direction.

## Who is affected
One player, intermediate, roughly 1200 rated. Plays a few evenings a week.

## What happens today
Opens an engine app, loses, closes it. No progression, no explanation of what
went wrong.

## Pain, frequency and cost
Two or three abandoned sessions a week. The cost is not money; it is that a
hobby is quietly being given up.

## What a fix would be worth
Enough to justify a small desktop app. No budget for a subscription.

## Success criteria
- A game that is close rather than one-sided.
- After a loss, a plain-English explanation of the moment it turned.
- Runs offline on one Mac.

## Unknowns and risks
- Whether "close game" can be achieved without the opponent playing obviously
  badly. This is the central design risk.
- Assumption, not fact: the player wants to improve rather than only to win.`,
    },
  ],
  2: [
    {
      kind: "solution_constraints",
      title: "Solution constraints",
      body: `# Solution constraints

## Solution form
Desktop application. Excluded: hosted web (offline is a stated criterion), CLI
(the artifact is a board), mobile (not asked for).

## Target platforms and environments
macOS 13+ on Apple silicon. One machine.

## Privacy and data policy
Local only. Game history stays on the machine. No account.

## Integrations and credentials
None required. If move explanation uses a model, it must be a local endpoint or
an explicitly configured key — never a silent cloud call.

## Non-goals
Online play, ratings ladders, opening databases, mobile.

## Unknowns
Whether the explanation feature can run locally at acceptable latency.`,
    },
  ],
  3: [
    {
      kind: "chosen_approach",
      title: "Chosen approach",
      body: `# Solution proposal

## Approach A — strength-matched engine with post-game review
A conventional engine, deliberately limited by search depth and a blunder
model tuned to the player's recent results, plus a review pass that names the
single move where the evaluation swung most.

## Approach B — teaching-first, fixed weak opponent
Simpler, but a fixed opponent stops being interesting within weeks.

## Recommendation
Approach A. The brief's central criterion is the close game, and B cannot hold
it as the player improves.`,
    },
  ],
  4: [
    {
      kind: "design_artifact",
      title: "GUI design",
      body: `# GUI design

## Screens
- Board (the whole window; no chrome beyond a status line).
- Post-game review (the move the evaluation swung on, in plain English).

## Interaction
Drag to move, or click source then destination. Illegal moves silently
snap back rather than raising a dialog.

## Visual language
A plain wooden-board palette, no theme switcher for v1. Captured pieces held
along either edge.`,
    },
  ],
  5: [
    {
      kind: "audience_package",
      title: "Audience package: is this the right shape?",
      body: `# Audience package

## What is being reviewed
The GUI design against the brief's success criteria: a close game, a
plain-English explanation after a loss, offline on one Mac.

## Open questions for reviewers
- Does the review screen read as an explanation or as a scorecard?
- Is drag-only interaction enough, or does the click-click path matter for
  accessibility?

## Audience: Project owner

### Deck outline

1. **Problem: chess practice without an explanation**
   A player loses and learns nothing from it.
2. **Proposed solution: a close game that explains the loss**
   One Mac, offline, a plain-English review after each game.
3. **Decision: build the design as shown**
   Approve the GUI design against the brief's success criteria.

### Decision request
- Approve the design, or send it back with what to change.`,
    },
  ],
  6: [
    {
      kind: "product_requirements",
      title: "Product requirements",
      body: `# Product requirements

Gathered from stages 1-4 into the one document the build plan is written
against.

## Must
- Legal-move-only board with drag and click-click input.
- Post-game review naming the single move the evaluation swung on.
- Runs fully offline.

## Should
- Configurable opponent strength within the tuned blunder model.

## Won't (v1)
- Online play, accounts, mobile.`,
    },
    {
      kind: "build_plan",
      title: "Build plan",
      body: `# Build plan

## Milestones
1. Board and legal-move engine (SwiftUI + a bundled UCI engine).
2. Blunder model tuned against a fixed corpus of recent games.
3. Post-game review pass naming the swing move.
4. Packaging as a signed, notarized .app.

## Test plan
Play out a fixed set of recorded games against the tuned opponent and check
the review pass names the same swing move a strong engine would.`,
    },
  ],
  7: [
    {
      kind: "cost_approval",
      title: "Cost approval",
      body: `# Cost approval

## Forecast
About 40 hours of build time against the plan's four milestones, well inside
the workspace's cost tolerance.

## Assumptions
- The bundled UCI engine is free to redistribute.
- No paid model endpoint is required for the review pass.`,
    },
  ],
};

const DELIVERED_BYTES = Buffer.from("the delivered application bytes, fixed and repeatable\n");
const DELIVERED_SHA = createHash("sha256").update(DELIVERED_BYTES).digest("hex");

const REASON = {
  routed: "Seeded: routed back for a worked example of a rejected stage.",
  failed: "Seeded: failed for a worked example of a failed run.",
  cancelled: "Seeded: cancelled for a worked example of a cancelled run.",
} as const;

const POLICY = {
  costTolerancePercent: 12,
  costToleranceAbsolute: 2100,
  audiences: [
    { name: "Project owner", role: "project_owner" as const },
    { name: "Budget owner", role: "budget_approver" as const },
  ],
  audienceQuorum: 2,
  allowExternalProviders: true,
};

// --- what this script can seed -----------------------------------------
//
// Every StageState and BuildState from packages/solutions-builder/src/ledger.ts
// that a command can actually land a run on is listed in CATALOG below, one
// row per reachable (stage, state) pair.

/** Every combination this script knows how to reach, and a one-line note on why. */
const CATALOG: { stage: Stage; state: string; note: string }[] = [
  ...([1, 2, 3, 4, 5, 6] as Stage[]).flatMap((stage) => [
    { stage, state: "in_progress" as const, note: "freshly entered, nothing drafted yet" },
    { stage, state: "waiting_approval" as const, note: "drafted and submitted, awaiting review" },
    { stage, state: "failed" as const, note: "the round was failed from in_progress" },
    { stage, state: "cancelled" as const, note: "the round was cancelled from in_progress" },
    {
      stage,
      state: "backtracked" as const,
      note: stage === 6 ? "routed back from stage 7" : `routed back from stage ${stage + 1}`,
    },
  ]),
  { stage: 5 as Stage, state: "waiting_approval_partial_quorum", note: "one of two audiences has decided; the other has not" },
  { stage: 7 as Stage, state: "in_progress", note: "freshly entered stage 7, nothing drafted yet" },
  { stage: 7 as Stage, state: "waiting_approval", note: "cost approval drafted and submitted" },
  { stage: 7 as Stage, state: "failed", note: "the round was failed from in_progress" },
  { stage: 7 as Stage, state: "cancelled", note: "the round was cancelled from in_progress" },
  { stage: 7 as Stage, state: "backtracked", note: "routed back from stage 8 (build.route_material_change)" },
  { stage: 7 as Stage, state: "cost_approved", note: "cost.approve recorded, not yet frozen" },
  { stage: 7 as Stage, state: "approved_frozen", note: "frozen: terminal, a build run now exists at stage 8" },
  { stage: 8 as Stage, state: "queued", note: "frozen, not yet started" },
  { stage: 8 as Stage, state: "running", note: "an attempt is running" },
  { stage: 8 as Stage, state: "waiting_human", note: "PARKED MID-ATTEMPT: the worker asked a question and is waiting on a person" },
  { stage: 8 as Stage, state: "interrupted", note: "PARKED MID-ATTEMPT: interrupted with a checkpoint retained, resumable" },
  { stage: 8 as Stage, state: "failed", note: "the attempt failed" },
  { stage: 8 as Stage, state: "cancelled", note: "the attempt was cancelled" },
  { stage: 8 as Stage, state: "evidence_accepted", note: "evidence accepted; a stage-9 delivery review now exists" },
  { stage: 9 as Stage, state: "delivery_review", note: "evidence accepted, awaiting the delivery decision" },
  { stage: 9 as Stage, state: "delivered", note: "the delivered bytes matched their manifest and were accepted" },
  { stage: 9 as Stage, state: "archived", note: "delivered, then archived" },
  { stage: 1 as Stage, state: "deleted", note: "project.delete: a tombstoned project (any stage works; the project never becomes readable again)" },
];

const UNSEEDABLE: { stage: Stage; state: string; reason: string }[] = [
  {
    stage: 8 as Stage,
    state: "backtracked",
    reason:
      "build.route_material_change does leave the source build run labelled backtracked, but it is terminal history: the project's current position moves to the earlier stage's new run. Ask for --stage 7 --state backtracked, which is that same transition, seen from the run that is actually current afterward.",
  },
  { stage: 9 as Stage, state: "backtracked", reason: "delivery.reject/revise route to an earlier stage's run; stage 9 itself never carries backtracked" },
  { stage: 9 as Stage, state: "failed", reason: "a stage-9 run is only ever created already at delivery_review — it has no in_progress to fail from" },
  { stage: 9 as Stage, state: "cancelled", reason: "same as failed: stage 9 has no in_progress" },
  { stage: 9 as Stage, state: "in_progress", reason: "stage 9 is created directly at delivery_review by build.accept_evidence" },
];

if (LIST) {
  console.log("Seedable stage/state combinations:\n");
  for (const entry of CATALOG) console.log(`  --stage ${entry.stage} --state ${entry.state}\n      ${entry.note}`);
  console.log("\nNot reachable through any command a person or the host could issue:\n");
  for (const entry of UNSEEDABLE) console.log(`  --stage ${entry.stage} --state ${entry.state}\n      ${entry.reason}`);
  process.exit(0);
}

const stageArg = arg("stage");
const stateArg = arg("state");
if (!stageArg || !stateArg) usage();
const targetStage = Number(stageArg) as Stage;
if (!Number.isInteger(targetStage) || targetStage < 1 || targetStage > 9) {
  console.error(`--stage must be 1-9, got ${stageArg}`);
  process.exit(1);
}
const targetState = stateArg;

const unseedable = UNSEEDABLE.find((entry) => entry.stage === targetStage && entry.state === targetState);
if (unseedable) {
  console.error(`Cannot seed stage ${targetStage} state "${targetState}": ${unseedable.reason}`);
  console.error(`Run with --list to see every seedable combination.`);
  process.exit(1);
}
const known =
  targetState === "deleted" ||
  CATALOG.some((entry) => entry.stage === targetStage && entry.state === targetState);
if (!known) {
  console.error(`Unknown combination: --stage ${targetStage} --state ${targetState}`);
  console.error(`Run with --list to see every seedable combination.`);
  process.exit(1);
}

// --- bootstrap, same as scripts/seed-demo.ts ---------------------------

const host = await openDatabase(databaseDirectory());
await prepareDatabase(host);
await ensureHub();
await install();
const ACTOR: Actor = { ...localActor(), displayName: "You" };
const HOST_ACTOR: Actor = { principalId: HOST_PRINCIPAL, displayName: "Solutions Builder host" };

async function command(
  type: Command,
  projectId: string,
  payload: Record<string, unknown>,
  actor: Actor = ACTOR,
): Promise<CommandOutcome> {
  return execute({
    type,
    actor,
    projectId,
    idempotencyKey: newId.command(),
    correlationId: newId.correlation(),
    payload,
  });
}

// --- deterministic title, and tombstoning any earlier seed under it ----

const title = `Seed: stage ${targetStage} ${targetState}`;

async function retireExisting(): Promise<void> {
  const existing = await listProjects();
  for (const project of existing.filter((entry) => entry.title === title)) {
    try {
      await command("project.delete", project.id, {});
    } catch (cause) {
      // Already deleted, or nothing left to delete — either way the slot is free.
      if (!(cause instanceof HostError)) throw cause;
    }
  }
}
await retireExisting();

// --- driving the project through the same commands a person would -----

type Version = { artifactId: string; versionId: string; contentHash: string };

async function currentRun(projectId: string) {
  const detail = await projectDetail(projectId, ACTOR.principalId);
  if (!detail.current) throw new Error("project has no current run");
  return detail.current;
}

/** Drafts and submits every artifact stage N owns, leaving the run waiting_approval at N. */
async function draftAndSubmit(projectId: string, runId: string, stage: 1 | 2 | 3 | 4 | 5 | 6 | 7): Promise<Version[]> {
  const versions: Version[] = [];
  for (const entry of ARTIFACTS_FOR_STAGE[stage]) {
    const node = await writeArtifact(
      {
        projectId,
        kind: entry.kind,
        title: entry.title,
        content: entry.body,
        mediaType: "text/markdown",
        sourceVersionIds: [],
        provenance: { producer: "human", runId },
      },
      ACTOR,
    );
    versions.push({ artifactId: node.artifactId, versionId: node.nodeId, contentHash: node.contentHash });
  }
  await command("stage.submit", projectId, { runId, versions });
  return versions;
}

/** Records both audiences deciding "proceed" — the full stage-5 quorum. */
async function decideFullQuorum(projectId: string, runId: string, versions: Version[]): Promise<void> {
  for (const audience of POLICY.audiences) {
    await command("audience.decide", projectId, {
      runId,
      audienceName: audience.name,
      decision: "proceed",
      versions,
    });
  }
}

/** Advances stages 1-6 through approval, stage 5's quorum included, up to (not including) targetStage. */
async function driveThroughApprovedStages(projectId: string, upTo: Stage): Promise<void> {
  for (let stage = 1; stage < upTo && stage <= 6; stage += 1) {
    const run = await currentRun(projectId);
    const versions = await draftAndSubmit(projectId, run.id, stage as 1 | 2 | 3 | 4 | 5 | 6);
    if (stage === 5) await decideFullQuorum(projectId, run.id, versions);
    await command("stage.approve", projectId, { runId: run.id, versions });
  }
}

/** Drives stage 7 through cost.approve, then build.freeze, leaving a queued build run at 8. */
async function driveThroughStage7(projectId: string): Promise<{ runId: string }> {
  const run = await currentRun(projectId);
  const versions = await draftAndSubmit(projectId, run.id, 7);
  await command("cost.approve", projectId, {
    runId: run.id,
    versions,
    forecastUsd: 1800,
    assumptions: ["Seeded: within the workspace's stated cost tolerance."],
  });
  const frozen = await command("build.freeze", projectId, {
    runId: run.id,
    versions,
    placement: "local",
    targets: ["cli"],
  });
  return { runId: frozen.runId };
}

/** Writes real, fixed bytes into a build run's workspace, matching DELIVERED_SHA. */
async function writeDeliveredBytes(buildRunId: string): Promise<void> {
  const workspace = await workspaceFor(buildRunId);
  await mkdir(join(workspace, "dist"), { recursive: true });
  await writeFile(join(workspace, "dist", "chess.app"), DELIVERED_BYTES);
}

/**
 * `build.accept_evidence` requires a genuine verifier report (BUILD_PLAN_V3
 * §7), so seeding a run past it runs the same completion judge a real
 * attempt would have, against the workspace as this script left it, rather
 * than fabricating a confidence level. No plan or requirements text is
 * seeded here, so the mechanical ceiling — never an inference call — decides
 * the level, exactly as `judgeCompletion` does for any workspace with
 * nothing to interpret semantics into.
 */
async function verifierReportFor(buildRunId: string): Promise<VerifierReport> {
  const workspace = await workspaceFor(buildRunId);
  const verdict = await judgeCompletion({ workspaceRoot: workspace, plan: "", requirements: "" });
  return verifierReportOf(verdict);
}

async function report(projectId: string): Promise<void> {
  const detail = await projectDetail(projectId, ACTOR.principalId);
  console.log(`\nSeeded "${detail.project.title}" (${projectId})`);
  console.log(`  requested: stage ${targetStage}, state ${targetState}`);
  for (const run of detail.runs) {
    console.log(`  run ${run.id.slice(0, 12)}…  kind=${run.kind}  stage=${run.stage}  state=${run.state}`);
  }
  if (detail.waits.length > 0) {
    console.log(`  ${detail.waits.length} decision waiting: ${detail.waits[0]?.title ?? ""}`);
  }
  if (detail.project.archivedAt) {
    console.log(`  project archivedAt=${new Date(detail.project.archivedAt).toISOString()}`);
  }
}

// --- run ----------------------------------------------------------------

if (targetState === "deleted") {
  const created = await createProject({ title, owner: ACTOR, policy: POLICY });
  await command("project.delete", created.projectId, {});
  console.log(`\nSeeded "${title}" (${created.projectId}) and deleted it.`);
  let refused = "";
  await projectDetail(created.projectId, ACTOR.principalId).catch((cause: unknown) => {
    refused = cause instanceof Error ? cause.message : String(cause);
  });
  console.log(`  reading it back is refused: ${refused || "(it was not refused — this is a bug)"}`);
  await host.close();
  process.exit(0);
}

const created = await createProject({ title, owner: ACTOR, policy: POLICY });
const { projectId } = created;

if (targetStage <= 6) {
  if (targetState === "backtracked") {
    // Reaching "backtracked" at N means a run one stage further was rejected
    // back to it — so this drives one stage past N, then routes back.
    await driveThroughApprovedStages(projectId, (targetStage + 1) as Stage);
    const run = await currentRun(projectId);
    await draftAndSubmit(projectId, run.id, (targetStage + 1) as 1 | 2 | 3 | 4 | 5 | 6 | 7);
    await command("stage.reject", projectId, { runId: run.id, targetStage, reason: REASON.routed });
  } else {
    await driveThroughApprovedStages(projectId, targetStage);
    const run = await currentRun(projectId);

    if (targetState === "in_progress") {
      // Already here: driveThroughApprovedStages stopped one short of targetStage.
    } else if (targetState === "waiting_approval") {
      await draftAndSubmit(projectId, run.id, targetStage as 1 | 2 | 3 | 4 | 5 | 6);
    } else if (targetState === "waiting_approval_partial_quorum") {
      if (targetStage !== 5) {
        console.error(`waiting_approval_partial_quorum only applies to stage 5`);
        process.exit(1);
      }
      const versions = await draftAndSubmit(projectId, run.id, 5);
      await command("audience.decide", projectId, {
        runId: run.id,
        audienceName: POLICY.audiences[0]!.name,
        decision: "proceed",
        versions,
      });
    } else if (targetState === "failed") {
      await command("stage.fail", projectId, { runId: run.id, reason: REASON.failed });
    } else if (targetState === "cancelled") {
      await command("stage.cancel", projectId, { runId: run.id, reason: REASON.cancelled });
    } else {
      console.error(`Unknown state "${targetState}" for stage ${targetStage}`);
      process.exit(1);
    }
  }
} else if (targetStage === 7) {
  await driveThroughApprovedStages(projectId, 7);
  const run = await currentRun(projectId);

  if (targetState === "in_progress") {
    // Already here.
  } else if (targetState === "waiting_approval") {
    await draftAndSubmit(projectId, run.id, 7);
  } else if (targetState === "failed") {
    await command("stage.fail", projectId, { runId: run.id, reason: REASON.failed });
  } else if (targetState === "cancelled") {
    await command("stage.cancel", projectId, { runId: run.id, reason: REASON.cancelled });
  } else if (targetState === "cost_approved") {
    const versions = await draftAndSubmit(projectId, run.id, 7);
    await command("cost.approve", projectId, {
      runId: run.id,
      versions,
      forecastUsd: 1800,
      assumptions: ["Seeded: within the workspace's stated cost tolerance."],
    });
  } else if (targetState === "approved_frozen") {
    await driveThroughStage7(projectId);
  } else if (targetState === "backtracked") {
    const { runId: buildRunId } = await driveThroughStage7(projectId);
    await command("build.start_attempt", projectId, { runId: buildRunId });
    await command("build.route_material_change", projectId, {
      runId: buildRunId,
      targetStage: 7,
      reason: REASON.routed,
    });
  } else {
    console.error(`Unknown state "${targetState}" for stage 7`);
    process.exit(1);
  }
} else if (targetStage === 8) {
  await driveThroughApprovedStages(projectId, 7);
  const { runId: queuedRunId } = await driveThroughStage7(projectId);

  if (targetState === "queued") {
    // Already here.
  } else {
    const started = await command("build.start_attempt", projectId, { runId: queuedRunId });
    const runningRunId = started.runId;

    if (targetState === "running") {
      // Already here.
    } else if (targetState === "waiting_human") {
      await command(
        "build.wait_for_human",
        projectId,
        { runId: runningRunId, kind: "permission", prompt: "Seeded: the build wants to install a dependency. Approve?" },
        HOST_ACTOR,
      );
    } else if (targetState === "interrupted") {
      await command("build.interrupt", projectId, { runId: runningRunId, reason: "Seeded: parked mid-attempt with a checkpoint." });
    } else if (targetState === "failed") {
      await command("build.fail", projectId, { runId: runningRunId, reason: REASON.failed });
    } else if (targetState === "cancelled") {
      await command("build.cancel", projectId, { runId: runningRunId, reason: REASON.cancelled });
    } else if (targetState === "evidence_accepted") {
      await writeDeliveredBytes(runningRunId);
      await command("build.accept_evidence", projectId, {
        runId: runningRunId,
        versions: [],
        verifierReport: await verifierReportFor(runningRunId),
        descriptors: [
          {
            category: "source",
            path: "dist/chess.app",
            sha256: DELIVERED_SHA,
            sizeBytes: DELIVERED_BYTES.byteLength,
            mediaType: "application/octet-stream",
            access: "local",
            required: true,
          },
        ],
        verification: { requiredChecks: "seeded" },
        actualCost: 12.5,
      });
    } else {
      console.error(`Unknown state "${targetState}" for stage 8`);
      process.exit(1);
    }
  }
} else if (targetStage === 9) {
  await driveThroughApprovedStages(projectId, 7);
  const { runId: queuedRunId } = await driveThroughStage7(projectId);
  const started = await command("build.start_attempt", projectId, { runId: queuedRunId });
  const runningRunId = started.runId;
  await writeDeliveredBytes(runningRunId);
  const accepted = await command("build.accept_evidence", projectId, {
    runId: runningRunId,
    versions: [],
    verifierReport: await verifierReportFor(runningRunId),
    descriptors: [
      {
        category: "source",
        path: "dist/chess.app",
        sha256: DELIVERED_SHA,
        sizeBytes: DELIVERED_BYTES.byteLength,
        mediaType: "application/octet-stream",
        access: "local",
        required: true,
      },
    ],
    verification: { requiredChecks: "seeded" },
    actualCost: 12.5,
  });
  const deliveryRunId = accepted.runId;

  if (targetState === "delivery_review") {
    // Already here.
  } else if (targetState === "delivered" || targetState === "archived") {
    await command("delivery.accept", projectId, {
      runId: deliveryRunId,
      manifestVersion: { artifactId: "-", versionId: "-", contentHash: "0".repeat(64) },
    });
    if (targetState === "archived") {
      await command("project.archive", projectId, { runId: deliveryRunId });
    }
  } else {
    console.error(`Unknown state "${targetState}" for stage 9`);
    process.exit(1);
  }
}

await report(projectId);
await host.close();
